### ISSUE TITLE
Problem setting theme

### ISSUE THREAD

**Issue by STaRDoGG** [TimWolla/docker-adminer#55] opened 2019-07-09 21:30 UTC
Heyoo,

So I'm trying to set the theme to pepa-linha, and it just won't take.

Whether I create container with the environment var like this:

`docker run -d --link mysql:db -p 90210:8080 --network=my-db -e ADMINER_DESIGN="pepa-linha" -e "ADMINER_PLUGINS=frames" --name adminer adminer`

or try to brute force it by starting the container with the adminer.css file stored on the host machine like this:

`docker run -d --link mysql:db -p 90210:8080 --network=my-db -e "ADMINER_PLUGINS=frames" --name adminer -v "/f/Sites/Web/.config/Adminer/adminer.css:/var/www/html/adminer.css" adminer`

The logs just show this when I run the container:

`/adminer/adminer.css - No such file or directory`

Any ideas? TIA

**Comment by Tintwo** [comment] 2019-07-10 08:40
I just tried right now with the `adminer:latest` tag and I can't reproduce your problem. It seems to work normally.

Are you sure you don't have another config problem ? Can you copy-paste precisely all messages when you put your _docker run [...]_ in your cli ?

Btw: what is exactly _it just won't take_ ? The port 90210 is not possible so you can't run a container with that local exposed port.

**Comment by STaRDoGG** [comment] 2019-07-10 15:51
Heya @Tintwo 

I will try to make a short vid of it happening a bit later when I get the chance.

Regarding the port, I just changed that for the post (can never be too cautious these days ;) ) , it's actually a 4 digit port in the correct range.

**Comment by TimWolla** [comment] 2019-07-10 15:53
@STaRDoGG The error message complains about `/adminer/adminer.css`. Are you running a reverse proxy in front of adminer?

**Comment by STaRDoGG** [comment] 2019-07-10 19:24
@TimWolla yezzir. I'm running Adminer in a [Nginx container](https://hub.docker.com/r/linuxserver/letsencrypt/), with a reverse proxy pointing to it.

**Comment by TimWolla** [comment] 2019-07-10 19:28
I believe this is a duplicate of #14 then.

**Comment by STaRDoGG** [comment] 2019-07-10 20:53
@TimWolla  interesting. I do also use the subfolder method (rather than the subdomain method) to reverse proxy it. Here's the Nginx code I'm using to do it:

```
location /adminer {
    return 301 $scheme://$http_host/adminer/;
}
location ^~ /adminer/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_adminer adminer;
    proxy_pass http://$upstream_adminer:8080;
}
```

I'd prefer to do it that way than have to go add a new cname to my DNS, etc.

Here's a screenshot of the Adminer container's log after visiting the Adminer page. Other than the theme I haven't noticed any other issues, though I've also barely used it. I've just been getting things setup at the moment.

![image](https://user-images.githubusercontent.com/1524526/61004115-de987c80-a32a-11e9-9ed4-59ce20568618.png)

**Comment by TimWolla** [comment] 2019-07-10 21:35
> I do also use the subfolder method (rather than the subdomain method) to reverse proxy it.

Yes, this is not supported by Adminer. Use the FastCGI version of this docker image, I've given an example configuration in #14.

**Closed by TimWolla** 2019-07-10 21:35 UTC
