### ISSUE TITLE
How to add sqlserver extension ?

### ISSUE THREAD

**Issue by konvergence** [TimWolla/docker-adminer#15] opened 2017-10-06 06:00 UTC
I try to add sql server extension.
I see that php-mssql (mssql_connect)  on  php5 and was removed in php7

So how can I do it on php7 ?  

Regards

**Comment by TimWolla** [comment] 2017-10-06 10:37
Try installing the `pdo_dblib` extension using `docker-php-ext-install
pdo_dblib`. It [is supported](
https://github.com/vrana/adminer/blob/master/adminer/drivers/mssql.inc.php#L237)
by Adminer for MS SQL and also is [part of the PHP tree](
https://github.com/php/php-src/tree/master/ext/pdo_dblib). I don't use SQL
Server myself and cannot comment on whether this extension works or not and
whether additional libraries are required.

Another driver that might work is `sqlsrv`:
http://php.net/manual/en/sqlsrv.installation.php. It is compatible with
Linux since version 4.0 according to the documentation. I cannot comment on
this extension either.

2017-10-06 8:00 GMT+02:00 konvergence <notifications@github.com>:

**Comment by konvergence** [comment] 2017-10-06 11:41
Thanks a lot !
I was able to build  and connect to sqlserver with the 1st solution (pdo_dlib)
Here the dockerfile for that : 


```
FROM adminer

USER root
RUN apk add --no-cache --virtual .php-ext-deps \
       unixodbc freetds

RUN   apk add --no-cache --virtual .build-deps \
        unixodbc-dev freetds-dev

RUN docker-php-ext-configure pdo_odbc --with-pdo-odbc=unixODBC,/usr 


RUN docker-php-ext-install \
           pdo_odbc pdo_dblib

RUN  apk del .build-deps \
 && rm -rf /var/cache/apk/*


USER adminer
CMD	[ "php", "-S", "[::]:8080", "-t", "/var/www/html" ]
EXPOSE 8080
```

**Comment by TimWolla** [comment] 2017-10-06 23:29
@konvergence Thanks for providing your solution! I'll thus close this issue.

**Closed by TimWolla** 2017-10-06 23:29 UTC

**Comment by hikmat30ce** [comment] 2018-08-17 12:28
I am geting below errors when building docker image from above dockerfile
`rm: can't remove '/usr/src/php/Zend/tests': Directory not empty
rm: can't remove '/usr/src/php/Zend': Directory not empty
rm: can't remove '/usr/src/php/ext/standard/tests/file': Directory not empty
rm: can't remove '/usr/src/php/ext/standard/tests': Directory not empty
rm: can't remove '/usr/src/php/ext/standard': Directory not empty
rm: can't remove '/usr/src/php/ext': Directory not empty
rm: can't remove '/usr/src/php': Directory not empty
The command '/bin/sh -c docker-php-ext-install            pdo_odbc pdo_dblib' returned a non-zero code: 1
`

**Comment by TimWolla** [comment] 2018-08-17 12:56
@hikmat30ce I'm unable to reproduce the issue. I copied the Dockerfile from above and built the image successfully:

[Dockerfile.txt](https://github.com/TimWolla/docker-adminer/files/2297240/Dockerfile.txt) invoked as:
```
$ docker build -t adminer:sqlserver -f Dockerfile.txt .
```

**Comment by hikmat30ce** [comment] 2018-08-17 15:13
I used the same command
`docker build -t adminer:sqlserver -f Dockerfile .`
and still geting same issue
I am using centos with below information
   `Static hostname: kafka-poc`
    `     Icon name: computer-vm`
    `       Chassis: vm`
    `    Machine ID: 7a8b2b7e56af4d6fa305434a09f92fb9`
    `       Boot ID: 7c817a9176064d86806f6cd7d067ed74`
    `Virtualization: microsoft`
	`Operating System: CentOS Linux 7 (Core)`
    `   CPE OS Name: cpe:/o:centos:centos:7`
    `        Kernel: Linux 3.10.0-327.28.2.el7.x86_64`
    `  Architecture: x86-64`

**Comment by alenhodzic85** [comment] 2019-09-24 08:18
Thank you very much, this works in Openshift also.

**Comment by staff0rd** [comment] 2020-01-28 21:05
I'm new to (and currently still wowing over) adminer, thanks for making this docker image available @TimWolla.  Also came here to determine the mssql solution, and confirmed @konvergence's Dockerfile works great and builds very quickly.

It is not clear why the mssql dependencies are not included with the official image.  Is there any appetite to either a) include them in the official image or b) have another tagged image (`adminer:mssql` or similar?) that includes them?

**Comment by TimWolla** [comment] 2020-02-03 12:04
@staff0rd Sorry for getting back to you only just know. I've read the email notification and then forgot about it.

> It is not clear why the mssql dependencies are not included with the official image.

Mostly because I was unable to verify how it works and what libraries would be required, because I have no MS SQL experience (as indicated by my first reply to this issue).

>  Is there any appetite to either a) include them in the official image

Yes, I guess we can do that. Would you like to create a *tested* PR that makes the necessary adjustments by modifying the existing commands, basically following the best practices outlined here: https://github.com/docker-library/official-images/? Please also add a size comparison between the image without MS SQL and with MS SQL.

> b) have another tagged image (`adminer:mssql` or similar?) that includes them?

Unless MS SQL bloats the image size by large I don't see why we couldn't include it in the default image.
